version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker_db
    ports:
      - "5432:5432"
